min_version = "2026.7.5"

[tools]
"1password-cli" = "latest"
rust = "1.95.0"
go = "latest"
python = "latest"
zig = "0.16.0"
uv = "latest"
"npm:pnpm" = "latest"
"npm:hunkdiff" = "latest"
bun = "latest"
node = "26.1.0"
ruby = "4"
"aqua:tealdeer-rs/tealdeer" = "latest"
"github:MarcoLucidi01/ytcast" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
bat = "latest"
chezmoi = "latest"
eza = "0.23.4"
fd = "latest"
fzf = "latest"
gh = "latest"
"git-lfs" = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
restic = "latest"
watchexec = "latest"
xcodes = "latest"
yt-dlp = "latest"
zoxide = "latest"
hk = "latest"
gitleaks = "latest"
"npm:agent-browser" = "latest"

[bootstrap.packages]
"brew:aria2" = "latest"
"brew:ffmpeg" = "latest"
"brew:fish" = "latest"
"brew:git" = "latest"
"brew:glances" = "latest"
"brew:htop" = "latest"
"brew:ifstat" = "latest"
"brew:libyaml" = "latest"
"brew:mosh" = "latest"
"brew:parallel" = "latest"
"brew:pkgconf" = "latest"
"brew:tmux" = "latest"
"brew-cask:1password" = "latest"
"brew-cask:adguard" = "latest"
"brew-cask:choosy" = "latest"
"brew-cask:cleanshot" = "latest"
"brew-cask:font-jetbrains-mono-nerd-font" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:iina" = "latest"
"brew-cask:orbstack" = "latest"
"brew-cask:raycast" = "latest"
"brew-cask:sf-symbols" = "latest"
"brew-cask:supacode" = "latest"
"brew-cask:telegram" = "latest"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"

[settings]
minimum_release_age = "3d"
minimum_release_age_excludes = ["npm:@openai/codex"]
lockfile_platforms = ["macos-arm64"]
trusted_config_paths = [
  "~/code/github.com/khoi",
  "~/code/github.com/supabitapp",
]
