[tools]
"1password-cli" = "latest"
rust = "1.95.0"
go = "latest"
python = "latest"
zig = "0.16.0"
uv = "latest"
"npm:pnpm" = "latest"
"npm:hunkdiff" = "latest"
bun = "latest"
node = "26.1.0"
ruby = "4"
"github:MarcoLucidi01/ytcast" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
bat = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
"git-lfs" = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
restic = "latest"
watchexec = "latest"
xcodes = "latest"
yt-dlp = "latest"
zoxide = "latest"
hk = "latest"
gitleaks = "latest"

[bootstrap.packages]
"brew:aria2" = "latest"
"brew:fish" = "latest"
"brew:git" = "latest"
"brew:glances" = "latest"
"brew:htop" = "latest"
"brew:ifstat" = "latest"
"brew:libyaml" = "latest"
"brew:mosh" = "latest"
"brew:parallel" = "latest"
"brew:pkgconf" = "latest"
"brew:tealdeer" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
trusted_config_paths = ["~/code/github.com/khoi","~/code/github.com/supabitapp", "~/.supacode"]
idiomatic_version_file = true
paranoid = false
