#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger window_focus"
sudo yabai --load-sa

move_to_space() {
  id=$(yabai -m query --windows | jq ".[] | select(.app | contains(\"$1\")) | .id")

  if [ -n "$id" ]; then
    yabai -m window "$id" --space "$2"
  fi
}

yabai -m config external_bar               all:35:0     \
                mouse_follows_focus        off          \
                focus_follows_mouse        autofocus    \
                window_zoom_persist        on           \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.2          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_animation_duration  0.0          \
                split_ratio                0.50         \
                auto_balance               off          \
                auto_padding               on           \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                4            \
                bottom_padding             4            \
                left_padding               4            \
                right_padding              4            \
                window_gap                 6

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(CleanShot X|Software Update|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Steam|Activity Monitor|Finder|1Password|Toggl Track)$" manage=off
yabai -m rule --add label="Arc PiP" app="^Arc$" title="^$" manage=off mouse_follows_focus=off
yabai -m rule --add label="Little Arc Launcher" app="^Arc$" title="^Space 1$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# Ignore everything without title
yabai -m rule --add label="" app=".+" title="^$" manage=off mouse_follows_focus=off
yabai -m rule --add label="untitled" app=".+" title="^$" manage=off mouse_follows_focus=off

SPACE_COUNT=$(yabai -m query --spaces --display 1 | jq length)

# Create more spaces if insufficient
if [ "$SPACE_COUNT" -lt 4 ]; then
  for _i in $(seq 1 $((4 - SPACE_COUNT))); do
    yabai -m space --create
  done
fi

# Label spaces
yabai -m space 1 --label "Browser"
yabai -m space 2 --label "Code"
yabai -m space 3 --label "Misc"

# Move all windows to Space Misc by default
yabai -m rule --add app=".*" label="All Apps" space=3
yabai -m rule --remove "All Apps"

# Spaces
## Space 1: Browser
# yabai -m rule --add app="kitty" title=".+" space=Browser
move_to_space "Arc" Browser
move_to_space "Safari" Browser

## Space 2: Code
# yabai -m rule --add app="Code" title=".+" space=Code
move_to_space "Code" Code
move_to_space "Xcode" Code
move_to_space "Alacritty" Code

yabai -m config layout bsp

# borders
borders active_color=0xffe78a4e inactive_color=0xff404344 width=4.0 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
