command_timeout = 200

[aws]
disabled = true

[ruby]
disabled = true

[java]
disabled = true

[gradle]
disabled = true

[kotlin]
disabled = true

[nodejs]
disabled = true

[git_status]
disabled = true
