-- Generated by switch-theme from themes/flexoki-light
vim.g.switch_theme = { name = "flexoki-light", colorscheme = "flexoki-light", background = "light" }

return {
  {
    "kepano/flexoki-neovim",
    priority = 1000,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "flexoki-light",
    },
  },
}
