-- Generated by switch-theme from themes/kanagawa
vim.g.switch_theme = { name = "monokai-nightasty", colorscheme = "monokai-nightasty", background = "dark" }

return {
	{
		"polirritmico/monokai-nightasty.nvim",
		priority = 1000,
		opts = {
			auto_enable_plugins = true,
			dark_style_background = "default",
			light_style_background = "default",
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "monokai-nightasty",
		},
	},
}
