-- Generated by switch-theme from themes/kanagawa
vim.g.switch_theme = {
	name = "srcery-gruvbox",
	colorscheme = "srcery",
	dark_colorscheme = "srcery",
	light_colorscheme = "gruvbox",
	background = "dark",
}

return {
	{ "srcery-colors/srcery-vim" },
	{
		"ellisonleao/gruvbox.nvim",
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "srcery",
		},
	},
}
