#!/usr/bin/env zsh

# Load color scheme
source "$HOME/.config/sketchybar/colors.sh"

FONT_FACE="TX02 Nerd Font Mono"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=32 \
    color=$COLOR_TRANSPARENT \
    margin=0 \
    sticky=on \
    padding_left=23 \
    padding_right=23 \
    notch_width=230 \
    display=main

sketchybar --default \
    background.color=$COLOR_ITEM_BG \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:14.0" \
    label.color=$COLOR_TEXT_LIGHT \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item current_space left \
    --set current_space \
    background.color=$COLOR_CURRENT_SPACE \
    icon.color=$COLOR_TEXT_DARK \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=$COLOR_FRONT_APP \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=$COLOR_TEXT_DARK \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=$COLOR_TRANSPARENT \
    background.padding_left=-3 \
    icon= \
    icon.color=$COLOR_FRONT_APP \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=$COLOR_TRANSPARENT \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:14.0" \
    label.drawing=yes

sketchybar --add item weather.moon q \
    --set weather.moon \
    background.color=$COLOR_MOON_BG \
    background.padding_right=-1 \
    icon.color=$COLOR_MOON_ICON \
    icon.font="$FONT_FACE:Bold:22.0" \
    icon.padding_left=4 \
    icon.padding_right=3 \
    label.drawing=off \
    --subscribe weather.moon mouse.clicked

sketchybar --add item weather q \
    --set weather \
    icon= \
    icon.color=$COLOR_WEATHER \
    icon.font="$FONT_FACE:Bold:15.0" \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=$COLOR_CLOCK \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item github_prs right \
    --set github_prs \
    icon=󰊤 \
    icon.color=$COLOR_TEXT_LIGHT \
    label.font="$FONT_FACE:Bold:14.0" \
    update_freq=300 \
    script="$PLUGIN_SHARED_DIR/github_prs.sh" \
    --subscribe github_prs mouse.clicked

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=$COLOR_VOLUME \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change

sketchybar --update
sketchybar --trigger space_change
