#!/usr/bin/env zsh
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Goodnotes - Generate Build from @bot
# @raycast.mode silent
# @raycast.packageName Goodnotes

# Optional parameters:
# @raycast.icon 📦
# @raycast.argument1 { "type": "text", "placeholder": "branch-name", "optional": true }

# Documentation:
# @raycast.author khoiracle
# @raycast.authorURL https://raycast.com/khoiracle

set -Eeuo pipefail
REPONAME="Goodnotes/GoodNotes-5"
# Get branch name from git if $1 is not set
BRANCH_NAME=${1:-$(cd /Users/khoi/Developer/code/github.com/GoodNotes/GoodNotes-5/ && git rev-parse --abbrev-ref HEAD)}
gh pr comment "$BRANCH_NAME" -R "$REPONAME" -b "/builds -v 6.0206.0"
