#!/bin/sh

# Get basename and normalize using parameter expansion
path_name="$(basename "$PWD")"
# Replace all non-alphanumeric characters (except dash and underscore) with underscore
path_name="${path_name//[^[:alnum:]_-]/_}"
# If path_name starts with a dash, prefix with underscore to avoid option parsing issues
if [[ "$path_name" == -* ]]; then
  path_name="_$path_name"
fi
session_name=${1-$path_name}

ZJ_SESSIONS=$(zellij list-sessions -n -s)
NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)

not_in_zellij() {
  [ -z "$ZELLIJ" ]
}

session_exists() {
  zellij list-sessions -ns | sed -E 's/:.*$//' | grep -q "^$session_name$"
}

create_detached_session() {
  zellij attach -cb "$session_name"
}

create_if_needed_and_attach() {
  if not_in_zellij; then
    zellij attach -c "$session_name"
  else
    if ! session_exists; then
      create_detached_session
    fi
  fi
}

create_if_needed_and_attach
