#!/bin/sh

printf '%s\n' \
  'Homebrew CLI is not installed. Use mise:' \
  '' \
  'Install an untracked formula:' \
  '  mise bootstrap packages apply brew:<formula> --yes' \
  '' \
  'Install an untracked cask:' \
  '  mise bootstrap packages apply brew-cask:<cask> --yes' \
  '' \
  'Upgrade an untracked package:' \
  '  mise bootstrap packages upgrade brew:<formula> --yes' \
  '' \
  'Do not use `mise bootstrap packages use` unless it should be tracked.' \
  'Do not use `mise bootstrap packages prune`; it removes untracked formulae.'

exit 127
