#!/bin/sh
#
# Attach or create tmux session named the same as current directory.

if [ -d "$1" ]; then
  root_dir="$1"
  path_name="$(basename "$1" | tr . -)"
else
  root_dir="$PWD"
  path_name="$(basename "$PWD" | tr . -)"
fi

session_name=${2-$path_name}

not_in_tmux() {
  [ -z "$TMUX" ]
}

session_exists() {
  tmux has-session -t "=$session_name" 2>/dev/null
}

create_detached_session() {
  (TMUX='' tmux new-session -Ad -s "$session_name" -c "$root_dir")
}

create_if_needed_and_attach() {
  if not_in_tmux; then
    exec tmux new-session -As "$session_name" -c "$root_dir"
  fi

  session_exists || create_detached_session
  tmux switch-client -t "=$session_name"
}

create_if_needed_and_attach
