live_config_reload = true

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetbrainsMono Nerd Font"

[font.italic]
family = "JetbrainsMono Nerd Font"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 2
y = 0

[hints]
alphabet = "hutenosadigpc.r,l'"

[[hints.enabled]]
regex = """(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
    [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
hyperlinks = true
post_processing = true
command = "open"
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
regex = """(/?[^/ \"']*[a-zA-Z0-9][^/ \"':]*/([^/ \"']+/?)*)\
    |(/[^/ \"']*[a-zA-Z0-9][^/ \"']*)"""
action = "Copy"
binding = { key = "P", mods = "Control|Shift" }
