live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetbrainsMono Nerd Font"

[font.italic]
family = "JetbrainsMono Nerd Font"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 2
y = 0

[hints]
alphabet = "hutenosadigpc.r,l'"

[[hints.enabled]]
regex = """(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
    [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
hyperlinks = true
post_processing = true
command = "open"
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
regex = """(?P<match>([.\\w\\-@$~\\[\\]]+)?(\\/[.\\w\\-@$\\[\\]]+)+)|(/[^/ \"']*[a-zA-Z0-9][^/ \"']*)|([a-f0-9]{40}|[a-f0-9]{7,8})|((?:[0-9]{1,3}\\.){3}[0-9]{1,3})"""
action = "Copy"
binding = { key = "P", mods = "Control|Shift" }
