[[mgr.prepend_keymap]]
on = "l"
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"' --confirm
'''

[[mgr.prepend_keymap]]
on = "p"
run = "plugin --sync smart-paste"
desc = "Paste into the hovered directory or CWD"
